# Generated by Django 3.0.4 on 2020-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
