# Generated by Django 3.0.4 on 2020-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20200830_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
