# Generated by Django 3.0.4 on 2020-08-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20200830_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='post',
        ),
    ]
