# Generated by Django 3.0.4 on 2020-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_uploadimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
